
/**************************************************************
 *	
 *	explosion, 8 bit, 11025Hz,
 *	1 channel, 54899 bytes/channel
 *	Total Size: 1 * 54899 + 4 (header) = 54943 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/danielansher/Documents/CS 2261/DanielAnsher_FinalProject/explosion.wav
 *	Time-stamp: Tue Apr 19 19:12:01 2016
 *	
 **************************************************************/

#ifndef __EXPLOSIONH__
#define __EXPLOSIONH__

#define EXPLOSIONFREQ 11025
#define EXPLOSIONLEN 54899

extern const unsigned char explosion[54899];

#endif /* __EXPLOSIONH__ */
