
/**************************************************************
 *	
 *	levelup, 8 bit, 11025Hz,
 *	1 channel, 11944 bytes/channel
 *	Total Size: 1 * 11944 + 4 (header) = 11988 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/danielansher/Documents/CS 2261/DanielAnsher_FinalProject/levelup.wav
 *	Time-stamp: Thu Apr 07 17:42:59 2016
 *	
 **************************************************************/

#ifndef __LEVELUPH__
#define __LEVELUPH__

#define LEVELUPFREQ 11025
#define LEVELUPLEN 11944

extern const unsigned char levelup[11944];

#endif /* __LEVELUPH__ */
