
/**************************************************************
 *	
 *	No_Monkey, 8 bit, 11025Hz,
 *	1 channel, 162831 bytes/channel
 *	Total Size: 1 * 162831 + 4 (header) = 162875 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/danielansher/Documents/CS 2261/DanielAnsher_FinalProject/No Monkey.wav
 *	Time-stamp: Sun Apr 03 13:57:05 2016
 *	
 **************************************************************/

#ifndef __NO_MONKEYH__
#define __NO_MONKEYH__

#define NO_MONKEYFREQ 11025
#define NO_MONKEYLEN 162831

extern const unsigned char No_Monkey[162831];

#endif /* __NO_MONKEYH__ */
