
/**************************************************************
 *	
 *	OhGod, 8 bit, 11025Hz,
 *	1 channel, 198144 bytes/channel
 *	Total Size: 1 * 198144 + 4 (header) = 198188 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/danielansher/Documents/CS 2261/DanielAnsher_FinalProject/OhGod.wav
 *	Time-stamp: Thu Apr 21 19:10:49 2016
 *	
 **************************************************************/

#ifndef __OHGODH__
#define __OHGODH__

#define OHGODFREQ 11025
#define OHGODLEN 198144

extern const unsigned char OhGod[198144];

#endif /* __OHGODH__ */
