
/**************************************************************
 *	
 *	Oniku_Loop, 8 bit, 11025Hz,
 *	1 channel, 194202 bytes/channel
 *	Total Size: 1 * 194202 + 4 (header) = 194246 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/danielansher/Documents/CS 2261/DanielAnsher_FinalProject/Oniku Loop.wav
 *	Time-stamp: Sun Apr 03 13:56:14 2016
 *	
 **************************************************************/

#ifndef __ONIKU_LOOPH__
#define __ONIKU_LOOPH__

#define ONIKU_LOOPFREQ 11025
#define ONIKU_LOOPLEN 194202

extern const unsigned char Oniku_Loop[194202];

#endif /* __ONIKU_LOOPH__ */
