
/**************************************************************
 *	
 *	wechampions, 8 bit, 11025Hz,
 *	1 channel, 352977 bytes/channel
 *	Total Size: 1 * 352977 + 4 (header) = 353021 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/danielansher/Documents/CS 2261/DanielAnsher_FinalProject/wechampions.wav
 *	Time-stamp: Thu Apr 14 10:34:40 2016
 *	
 **************************************************************/

#ifndef __WECHAMPIONSH__
#define __WECHAMPIONSH__

#define WECHAMPIONSFREQ 11025
#define WECHAMPIONSLEN 352977

extern const unsigned char wechampions[352977];

#endif /* __WECHAMPIONSH__ */
